sudo: false
dist: bionic
language: python
python: 3.6.10
matrix:
    include:
        - env: HSTCAL=stable
        - env: HSTCAL=latest

install:
    - scripts/caldp-install-all  ${HSTCAL}
    - cp scripts/* /home/travis/.travis/functions
    - source caldp-config-offsite

script: tox
