sudo: false
dist: bionic
language: python
python: 3.6.10
env:
    global:   #  caldp-config-offsite
        - CRDS_PATH=$HOME/crds_cache
        - CRDS_SERVER_URL=https://hst-crds.stsci.edu
        - CRDS_READONLY_CACHE=0
        - iref=${CRDS_PATH}/references/hst/wfc3/
        - jref=${CRDS_PATH}/references/hst/acs/
        - oref=${CRDS_PATH}/references/hst/stis/
        - lref=${CRDS_PATH}/references/hst/cos/
        - nref=${CRDS_PATH}/references/hst/nicmos/
        - uref=${CRDS_PATH}/references/hst/wfcpc2/
        - uref_linux=$uref

jobs:
  # Don't wait for allowed failures
  fast_finish: true

  include:
    - name: Pytest functional tests STABLE
      install:
            - scripts/caldp-install-all  stable
      script:
            - source "$HOME/miniconda3/etc/profile.d/conda.sh"
            - conda activate caldp_stable
            - pytest caldp --cov=caldp --cov-report=term-missing

    - name: Pytest functional tests LATEST
      install:
            - scripts/caldp-install-all latest
      script:
            - source "$HOME/miniconda3/etc/profile.d/conda.sh"
            - conda activate caldp_stable
            - pytest caldp --cov=caldp --cov-report=term-missing

    - name: Black style checks
      script:
            - black --check caldp caldp/tests

    - name: Flake8 python lint checks
      script:
            - flake8 --count --max-line-length=120

    - name: Bandit security checks
      script:
            - bandit -r caldp

