sudo: false
dist: bionic
language: python
python: 3.6.10
env:
    global:   #  caldp-config-offsite
        - CRDS_PATH=$HOME/crds_cache
        - CRDS_SERVER_URL=https://hst-crds.stsci.edu
        - CRDS_READONLY_CACHE=0
        - iref=${CRDS_PATH}/references/hst/wfc3/
        - jref=${CRDS_PATH}/references/hst/acs/
        - oref=${CRDS_PATH}/references/hst/stis/
        - lref=${CRDS_PATH}/references/hst/cos/
        - nref=${CRDS_PATH}/references/hst/nicmos/
        - uref=${CRDS_PATH}/references/hst/wfcpc2/
        - uref_linux=$uref

jobs:
  # Don't wait for allowed failures
  fast_finish: true

  include:
    - name: Pytest functional tests
        matrix:
            include:
                - env: HSTCAL=stable
                - env: HSTCAL=latest
        install:
            - scripts/caldp-install-all  ${HSTCAL}
        script:
            - source "$HOME/miniconda3/etc/profile.d/conda.sh"
            - conda activate caldp_${HSTCAL}
            - pytest caldp --cov=caldp --cov-report=term-missing

    - name Black style checks
        script:
            black --check caldp caldp/tests

    -name Flake8 python lint checks
        script:
            flake8 --count caldp

    -name Bandit security checks
        script:
            bandit -r caldp

 #     - name: SDP dependencies in requirements-sdp.txt, CRDS_CONTEXT=jwst-edit
#       python: 3.7.7
#       env:
#         PIP_DEPENDENCIES="-r requirements-sdp.txt .[test]"
#         CRDS_CONTEXT=jwst-edit
#         TEST_COMMAND=pytest

#     - name: Dev dependencies in requirements-dev.txt
#       env:
#         PIP_DEPENDENCIES="-r requirements-dev.txt .[test]"
#         TEST_COMMAND=pytest

#     - name: Warnings treated as Exceptions
#       env:
#         TEST_COMMAND="pytest -W error"



# script:
#     - source "$HOME/miniconda3/etc/profile.d/conda.sh"
#     - conda activate caldp_${HSTCAL}
#     - pytest caldp --cov=caldp --cov-report=term-missing

