sudo: false
dist: bionic
language: python
python: 3.6.10
env:
    global:   #  caldp-config-offsite
        - CRDS_PATH=$HOME/crds_cache
        - CRDS_SERVER_URL=https://hst-crds.stsci.edu
        - CRDS_READONLY_CACHE=0
        - iref=${CRDS_PATH}/references/hst/wfc3/
        - jref=${CRDS_PATH}/references/hst/acs/
        - oref=${CRDS_PATH}/references/hst/stis/
        - lref=${CRDS_PATH}/references/hst/cos/
        - nref=${CRDS_PATH}/references/hst/nicmos/
        - uref=${CRDS_PATH}/references/hst/wfcpc2/
        - uref_linux=$uref
        - DOCKER_REPO=jaytmiller/caldp
        - DOCKER_TAG=latest
        - CAL_BASE_IMAGE=stsci/hst-pipeline:latest
        - CALDP_TEST_FILE_SIZE_THRESHOLD=0.30

jobs:
  # Don't wait for allowed failures
  fast_finish: true

  include:
    - name: Pytest native functional tests STABLE
      env:
        - HSTCAL=stable
        - LD_LIBRARY_PATH=$HOME/miniconda3/envs/caldp_${HSTCAL}/lib
      install:
        - scripts/caldp-install-all  ${HSTCAL}
      script:
        - source "$HOME/miniconda3/etc/profile.d/conda.sh"
        - conda activate caldp_${HSTCAL}
        - pytest caldp --cov=caldp --cov-fail-under 80  --capture=tee-sys
      after_success:
        - bash <(curl -s https://codecov.io/bash)

    - name: Pytest native functional tests LATEST
      env:
        - HSTCAL=latest
        - LD_LIBRARY_PATH=$HOME/miniconda3/envs/caldp_${HSTCAL}/lib
      install:
        - scripts/caldp-install-all  ${HSTCAL}
      script:
        - source "$HOME/miniconda3/etc/profile.d/conda.sh"
        - conda activate caldp_${HSTCAL}
        - pytest caldp --cov=caldp  --cov-fail-under 80  --capture=tee-sys
      after_success:
        - bash <(curl -s https://codecov.io/bash)

    - name: Docker image build and single dataset
      services: docker
      before_install:
        # - docker pull $DOCKER_REPO:$DOCKER_TAG
        - docker build -f Dockerfile  -t ${DOCKER_REPO}:${DOCKER_TAG}  --build-arg CAL_BASE_IMAGE=${CAL_BASE_IMAGE}  .
      script:
        - "docker run ${DOCKER_REPO}:${DOCKER_TAG}  caldp-process  j8cb010b0  astroquery:  none  caldp-config-offsite"
      after_success:
        - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
        - docker push ${DOCKER_REPO}:${DOCKER_TAG}

    - name: Black style checks
      install:
            - pip install black
      script:
            - black --check caldp caldp/tests

    - name: Flake8 python lint checks
      install:
            - pip install flake8
      script:
            - flake8 --count --max-line-length=120 --exclude docs

    - name: Bandit security checks
      install:
            - pip install bandit
      script:
            - bandit -ll -r caldp
