sudo: false
dist: bionic
language: python
python: 3.7
matrix:
    include:
        - env: TOXENV=stable
        - env: TOXENV=latest
        - env: TOXENV=black
        - env: TOXENV=flake8
        - env: TOXENV=coverage
        - env: TOXENV=bandit
install:
    - pip install tox tox-conda
script: tox
