#! /bin/bash

# Run commands in the CALDP container.
# Expose $HOME as $HOME in the container.
# Map (jupyter lab) container port 8888 to docker host port 8888.

docker run --rm -it -p 8888:8888 --mount type=bind,source=$HOME,target=/home/developer $CALDP_DOCKER_IMAGE $*
