#! /bin/bash

# For non-AWS desktop use based on pip install.  Docker must wrap this.

ipppssoot=$1
input_path=$2
output_path=$3
caldp_config=${4:-caldp-config-aws-crds}

caldp-process $ipppssoot  $input_path   $output_path   $caldp_config
