#! /bin/bash

set -eu
set -o pipefail

# Run the caldp unit tests passing any parameters to pytest
# useful parameters: -v -v -v,  --profile,   see pytest --help

export CALDP_DOCKER_RUN_PARS=${CALDP_DOCKER_RUN_PARS:-"-it --rm"}

( caldp-docker-run-container pytest  \
   -o log_cli=True \
   --log-level=INFO --log-cli-level=INFO \
   --color=no  --capture=no \
   --cov=caldp --cov-report=html:htmlcov \
   --doctest-modules caldp $* \
) 2>&1 | tee $CALDP_CLONE/test.log
