#! /bin/bash -e

ACCOUNT_ID=$(aws sts get-caller-identity | grep Account | cut -d'"' -f4)

awsudo ${ADMIN_ARN} aws ecr get-login-password --region=us-east-1 | docker login --username AWS --password-stdin ${ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com

