#! /bin/bash

# For testing with Docker image prior to submitting actual workflow jobs.
#
# For AWS usage including S3:
#
# $ caldp-docker-run-pipeline <tag> <s3_output_path> <ipppssoot>
#
# s3_output_path -- fully specified path for outputs to S3,
#                   includes both s3 bucket and batch subdirectory
#                   does not include instrument or ipppssoot subdirs.
#
# For laptop usage bypassing S3 actions:
#
# $ caldp-docker-run-pipeline  none <ipppssoot's...>

source  caldp-image-config $1
shift;

caldp-docker-run-container caldp-process $*
