#!/bin/bash

#
# this script outputs the environment variables used by the
# github actions for caldp in the necessary format, namely:
# var=value
# with no embedded variables in the value
#

set -o nounset

# HSTCAL must be passed in, usually either 'stable' or 'latest'
HSTCAL=$1

#
# all other variables must be set here, and referenced in the for loop below
#

LD_LIBRARY_PATH=${LD_LIBRARY_PATH:+$LD_LIBRARY_PATH:}$HOME/miniconda3/envs/caldp_$HSTCAL/lib

CRDS_SERVER_URL=https://hst-crds.stsci.edu
CRDS_READONLY_CACHE=0
CRDS_PATH=$HOME/crds_cache

CALDP_TEST_FILE_SIZE_THRESHOLD=0.30

iref=$CRDS_PATH/references/hst/wfc3/
jref=$CRDS_PATH/references/hst/acs/
oref=$CRDS_PATH/references/hst/stis/
lref=$CRDS_PATH/references/hst/cos/
nref=$CRDS_PATH/references/hst/nicmos/
uref=$CRDS_PATH/references/hst/wfcpc2/
uref_linux=$uref

CAL_BASE_IMAGE=stsci/hst-pipeline:$HSTCAL
DOCKER_REPO=alphasentaurii/caldp
DOCKER_TAG=$HSTCAL

for e in \
    HSTCAL \
    LD_LIBRARY_PATH \
    CRDS_SERVER_URL CRDS_READONLY_CACHE CRDS_PATH \
    CALDP_TEST_FILE_SIZE_THRESHOLD \
    iref jref oref lref nref uref uref_linux \
    CAL_BASE_IMAGE DOCKER_REPO DOCKER_TAG
do
    echo $e=${!e}
done
