name: code checks

on: [push, pull_request, workflow_dispatch]

jobs:
  bandit:
    name: run bandit
    runs-on: ubuntu-20.04

    steps:
      - name: set up python 3.8.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.11

      - name: install dependencies
        run: pip install bandit

      - name: checkout code
        uses: actions/checkout@v2

      - name: run bandit security checks
        run: bandit -ll -r caldp

  black:
    name: run black
    runs-on: ubuntu-20.04

    steps:
      - name: set up python 3.8.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.11

      - name: install dependencies
        run: pip install black

      - name: checkout code
        uses: actions/checkout@v2

      - name: run black style checks
        run: black --check caldp caldp/tests -l 120 -v

  flake8:
    name: run flake8
    runs-on: ubuntu-20.04

    steps:
      - name: set up python 3.8.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.11

      - name: install dependencies
        run: pip install flake8

      - name: checkout code
        uses: actions/checkout@v2

      - name: run flake8 python lint checks
        run: flake8 --count --max-line-length=120 --exclude docs
