name: docker

on: [push, pull_request, workflow_dispatch]

jobs:
  docker:
    name: docker image build and test
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        HSTCAL: [stable]

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: docker build
        run: |
          source caldp-setup
          caldp-image-build

      - name: run tests
        run: |
          source caldp-setup
          export CALDP_DOCKER_RUN_PARS="--rm --user root:root"  # non-interactive terminal, enable write this dir with root
          caldp-test

      - name: compute test coverage
        uses: codecov/codecov-action@v2

      - name: run sample container
        run: |
          source caldp-setup
          export CALDP_DOCKER_RUN_PARS="--rm --user root:root"  # non-interactive terminal, enable write this dir with root
          caldp-docker-run-pipeline j8cb010b0 astroquery: none caldp-config-offsite
